---
- hosts: centos
  tasks:
    - name: Install Web Server
      yum:
        name: httpd
        state: installed
      become: yes
    - name: Printing test mesage
      debug:
        msg: "Hello Test Message"
