---
- hosts: centos
  become: yes
  tasks: 
    - name: Install Web Srever
      yum:
        name: httpd
        state: installed
      notify: ReStart Web Server

  handlers:
    - name: ReStart Web Server
      action: service name=httpd state=restarted 
