---
- hosts: centos
  become: yes
  tasks: 
    - name: Install Web Srever
      yum:
        name: httpd
        state: installed
    - name: ReStart Web Server
      service:
        name: httpd
        state: restarted 
