---
- hosts: centos
  become: yes
  tasks:
    - name: Creating Sales group
      group:
        name: sales

    - name: Add User {{item}}
      user: 
        name: "{{item}}"
        group: sales
      with_items:
        - rama
        - raju
...
