---
- hosts: centos
  tasks: 
    - name: Create files and directories
      file:
        name: "/tmp/{{item[0]}}/{{item[1]}}"
        state: directory
      with_nested:
        - [ 'dir1', 'dir2', 'dir3' ]
        - [ 's1', 's2', 's3']
