---
- hosts: all
  become: true
  vars:
    pack_name: httpd
    serv_name: httpd
  tasks:
    - name: "Install package {{pack_name}}"
      yum: 
        name: "{{pack_name}}"
        state: latest

    - name: "Startservice {{serv_name}}"
      service:
        name: "{{serv_name}}"
        state: started
...
