---
- hosts: all
  vars_prompt:
    - name: username
      prompt: Enter Your Username
      private: no
    - name: password 
      prompt: Enter Your Password
  tasks:
    - name: Printing Username and Password
      debug: 
        msg: "Your Username = {{username}} :: Your Password = {{password}}"

...
