- name: Install Web Server
  yum: 
    name: "{{pack_name}}"
    state: installed
  when: ansible_distribution == "CentOS"

- name: Install Web Server
  apt: 
    name: "{{pack_name}}"
    state: installed
  when: ansible_distribution == "Ubuntu"

