- name: Create instance(s)
  hosts: localhost
  connection: local
  gather_facts: no

  vars:
    service_account_email: sample@demo3-158214.iam.gserviceaccount.com 
    credentials_file: /opt/demo3.json
    project_id: demo3-158214 
    machine_type: n1-standard-1
    image: debian-7

  tasks:

   - name: Launch instances
     gce:
         instance_names: dev
         machine_type: "{{ machine_type }}"
         image: "{{ image }}"
         service_account_email: "{{ service_account_email }}"
         credentials_file: "{{ credentials_file }}"
         project_id: "{{ project_id }}"
     register: out

   - name: Setting facts
     set_fact: 
        ipname: "{{ out.instance_data.name }}"

   - name: debugged output
     debug: 
        msg: "{{ipname}}"
