- name: Create Google Instance
  hosts: local
  tasks:
     - name: Create Instance
       gce:
         instance_name: demo1
         zone: us-central1-c
         machine_type: n1-standard-1
         image: debian-7-wheezy
         project_id: "demo3-158214"
         credentials_file: "/root/ansible/GCE.json"
         service_account_email: "harsha@demo3-158214.iam.gserviceaccount.com"
